spring:
  datasource:
    url: ${DB_URL_DOCKER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  data:
    redis:
      host: redis
      port: 6379
      timeout: 5000ms
      repositories:
        enabled: false  

  cache:
    redis:
      time-to-live: 30m

  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

auth:
  service:
    url: http://host.docker.internal:8082