management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8081

spring:
  application:
     name: user-service
  profiles:
    active: local
  liquibase: 
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

