spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      repositories:
        enabled: false  
  
  cache:
    redis:
      time-to-live: 30m

  jpa:
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: c3VwZXJTZWN1cmVTZWNyZXRLZXlGb3JKV1RDb25maWd1cmF0aW9uMTIz

auth:
  service:
    url: http://localhost:8082